general {
    gaps_in = 7
    gaps_out = 15

    border_size = 2

    col.active_border = rgb(665c54)
    col.inactive_border = rgb(3c3836)
    resize_on_border = true

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 3

    active_opacity = 0.9
    inactive_opacity = 0.85
    
    shadow {
        enabled = true
        range = 20
        render_power = 3 
        color = rgb(282828)
      }

    blur {
        enabled = true
        size = 6
        passes = 3

        vibrancy = 0.1696
    }
}
